[add] CRUDを追加
kenty51107/task-matcher pull request #4
Opened 2023-05-03 12:16 UTC by kenty51107

** 概要

- CRUDを実装中

** 詳細

- taskDelete以外(おそらく)実装完了(未テスト)

Q. gqlgenで自動生成されたresolver(adapter/handler/schema.resolvers.go)のdeleteのmutationの返り値に
　task構造体のポインタが指定されている.
　そこで以下の３項目がわかりません.
   - なぜレコードは削除されたのに構造体を返すのか？その構造体には何が入っているのか？
   - errorのみを返すのはダメなのか？
   - それともresolverの方を変更してもよいのか？

申し訳ないけど, 教えてください.

2023-05-03 12:44 UTC, yoji4910 commented
Q1. 別に構造体を返さなくてもいいよ. 何も返さなくてもいいし

2023-05-03 18:25 UTC, yoji4910 requested changes
いくつかコメントしたので、修正しre-requestしてください。

2023-05-03 18:25 UTC, yoji4910 commented on internal/app/infra/datastore/task_datastore.go
> +    if input.Schedule.IsZero() {
これ何の条件分岐？

2023-05-03 18:25 UTC, yoji4910 commented on internal/app/infra/datastore/task_datastore.go
> +        UpdatedAt: time.Now(),
細かいけど、時間がずれないように一旦変数に入れよう
```go
timestamp := time.Now()

CreatedAt: timestamp,
UpdatedAt: timestamp,
```

2023-05-03 18:25 UTC, yoji4910 commented on internal/app/infra/datastore/task_datastore.go
> +func (td *taskDatastore) FindTaskByID(taskId int) (*model.Task, error) {
細かいけど、命名ルール的にはこうかな？
```suggestion
func (td *taskDatastore) FindTaskByID(taskID int) (*model.Task, error) {
```

2023-05-03 18:25 UTC, yoji4910 commented on internal/app/infra/datastore/task_datastore.go
> +    return row, nil
updateのコードが抜けてる？

2023-05-03 19:15 UTC, kenty51107 commented on internal/app/infra/datastore/task_datastore.go
> +    if input.Schedule.IsZero() {
入力値がdatetime型のフォーマットと違っても(あるかわからないけど)
確実に日付が記録されるようにと入れました.
そのようなシュチュエーションがあるかもしれないと思い, 保険の意味で...

不必要な気もするので, 暫定的には削除しました.

2023-05-03 19:18 UTC, kenty51107 commented on internal/app/infra/datastore/task_datastore.go
> +func (td *taskDatastore) FindTaskByID(taskId int) (*model.Task, error) {
コード中の同様なフォーマットを以下に統一します.
  × *_Id --> ○ *_ID

例外として, schema.graphqls中の"id"は依然こままでいきます.

2023-05-03 19:18 UTC, kenty51107 commented on internal/app/infra/datastore/task_datastore.go
> +    return row, nil
抜けてました. すいません.

2023-05-04 03:34 UTC, yoji4910 approved these changes
LGTM!

2023-05-04 10:23 UTC, merged