[add] Feature/add validator
kenty51107/task-matcher pull request #6
Opened 2023-05-04 13:59 UTC by kenty51107

** 概要
- 指摘箇所の修正

** 詳細
- domain/model/task.go内のinput構造体自体にvalidateタグを付与
- infra/validator/task_validator.goを追加.
  - Validateメソッドを追加. 引数に得たオブジェクトを検証するもの.
  - GetValidateErrorメソッドを追加. バリデーションエラーをキャッチする機能.
- 改めてusecase/service/task_service.goでvalidateを実装
- .vscode/launch.jsonのコメントを削除
- graph/schema.graphqlの"!"を全てキャンセル.
  理由
  - バリデーションのrequiredが効かなくなる."!"がついていると, バリエーション前にgraphql自体がエラーを返してしまう.
  - 同時に生じた他のエラーが見えなる.

** 備考
レスポンスが遅くてすいません

//////////////////////////////////////////////////////////////////
** 概要
- validatorを実装

** 詳細
- validationをgo-ozzoからgo-playgroundに変更
- domain/modelのcreate, update, deleteのinput構造体のメソッドを定義.
- usecase/serviceでバリデートを実行している.

- 前回のプッシュできなかった, graphqlエンドポイント生成関数を改めて実装.
- 同様に漏れていた, deleteTask mutationを追加.

** 備考
ローカルでのブランチ管理がうまくいってません.
前回との差分であべこべな箇所が含まれている可能性があります.
同様の理由で, 新たにブランチをきってぷるりくしてます.

2023-05-04 15:47 UTC, yoji4910 requested changes

2023-05-04 15:47 UTC, yoji4910 commented on .vscode/launch.json
> +  // 詳細情報は次を確認してください: https://go.microsoft.com/fwlink/?linkid=830387
JSONにはコメント入れれないよ
問題なければこれでもいいけど

2023-05-04 15:47 UTC, yoji4910 commented on internal/app/domain/model/task.go
> +}
```
type CreateTaskInput struct {
	Title    string    `json:"title",validate:"required,max=100"`
        ...
}
```
みたいにして同様のことを実現できないか？
こうしない理由があるの？

2023-05-04 15:47 UTC, yoji4910 commented on graph/schema.graphqls
> +
前のPRにもあった気がする。差分がおかしい？

2023-05-04 20:36 UTC, kenty51107 commented on internal/app/domain/model/task.go
> +}
指摘の通りこっちの方がいいと思います.
ただ, modelにバリデーションのタグとも言えど, 直接書くのは,よろしくないと思ったため, usecaseにまとめる意図がありました.

2023-05-04 20:39 UTC, kenty51107 commented on graph/schema.graphqls
> +
その通りです.

2023-05-05 05:46 UTC, yoji4910 approved these changes
LGTM

2023-05-05 05:48 UTC, yoji4910 commented on graph/schema.graphqls
> +  updated_at: Time
もう変更しなくていいけど、可能な限り必須にしておいた方が扱いやすいけどね

2023-05-05 06:07 UTC, merged